// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: availability.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAvailability = `-- name: CreateAvailability :one
INSERT INTO service_availability (service_id, day_of_week, start_time, end_time)
VALUES ($1, $2, $3, $4)
RETURNING id, service_id, day_of_week, start_time, end_time, created_at, updated_at
`

type CreateAvailabilityParams struct {
	ServiceID uuid.UUID `json:"service_id"`
	DayOfWeek int16     `json:"day_of_week"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

func (q *Queries) CreateAvailability(ctx context.Context, arg CreateAvailabilityParams) (ServiceAvailability, error) {
	row := q.db.QueryRowContext(ctx, createAvailability,
		arg.ServiceID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	var i ServiceAvailability
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAvailabilityByID = `-- name: DeleteAvailabilityByID :exec
DELETE FROM service_availability
WHERE id = $1
`

func (q *Queries) DeleteAvailabilityByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAvailabilityByID, id)
	return err
}

const getAllAvailability = `-- name: GetAllAvailability :many
SELECT id, service_id, day_of_week, start_time, end_time, created_at, updated_at FROM service_availability
`

func (q *Queries) GetAllAvailability(ctx context.Context) ([]ServiceAvailability, error) {
	rows, err := q.db.QueryContext(ctx, getAllAvailability)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceAvailability
	for rows.Next() {
		var i ServiceAvailability
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailabilityByID = `-- name: GetAvailabilityByID :one
SELECT id, service_id, day_of_week, start_time, end_time, created_at, updated_at FROM service_availability
WHERE id = $1
`

func (q *Queries) GetAvailabilityByID(ctx context.Context, id uuid.UUID) (ServiceAvailability, error) {
	row := q.db.QueryRowContext(ctx, getAvailabilityByID, id)
	var i ServiceAvailability
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAvailabilityByServiceID = `-- name: GetAvailabilityByServiceID :many
SELECT id, service_id, day_of_week, start_time, end_time, created_at, updated_at FROM service_availability
WHERE service_id = $1
`

func (q *Queries) GetAvailabilityByServiceID(ctx context.Context, serviceID uuid.UUID) ([]ServiceAvailability, error) {
	rows, err := q.db.QueryContext(ctx, getAvailabilityByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceAvailability
	for rows.Next() {
		var i ServiceAvailability
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAvailabilityByID = `-- name: UpdateAvailabilityByID :one
UPDATE service_availability
SET service_id = $1, day_of_week = $2, start_time = $3, end_time = $4, updated_at = now()
WHERE id = $5
RETURNING id, service_id, day_of_week, start_time, end_time, created_at, updated_at
`

type UpdateAvailabilityByIDParams struct {
	ServiceID uuid.UUID `json:"service_id"`
	DayOfWeek int16     `json:"day_of_week"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAvailabilityByID(ctx context.Context, arg UpdateAvailabilityByIDParams) (ServiceAvailability, error) {
	row := q.db.QueryRowContext(ctx, updateAvailabilityByID,
		arg.ServiceID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.ID,
	)
	var i ServiceAvailability
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
