// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookings.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    customer_id, service_id, starts_at, ends_at,
    status, service_name, service_price,
    customer_notes, stripe_checkout_session_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, customer_id, service_id, starts_at, ends_at, status, service_name, service_price, customer_notes, stripe_checkout_session_id, stripe_payment_intent_id, paid_at, cancelled_at, created_at, updated_at
`

type CreateBookingParams struct {
	CustomerID              uuid.UUID      `json:"customer_id"`
	ServiceID               uuid.UUID      `json:"service_id"`
	StartsAt                time.Time      `json:"starts_at"`
	EndsAt                  time.Time      `json:"ends_at"`
	Status                  string         `json:"status"`
	ServiceName             string         `json:"service_name"`
	ServicePrice            interface{}    `json:"service_price"`
	CustomerNotes           sql.NullString `json:"customer_notes"`
	StripeCheckoutSessionID sql.NullString `json:"stripe_checkout_session_id"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.CustomerID,
		arg.ServiceID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Status,
		arg.ServiceName,
		arg.ServicePrice,
		arg.CustomerNotes,
		arg.StripeCheckoutSessionID,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ServiceID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.ServiceName,
		&i.ServicePrice,
		&i.CustomerNotes,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingByCheckoutID = `-- name: GetBookingByCheckoutID :one
SELECT id, customer_id, service_id, starts_at, ends_at, status, service_name, service_price, customer_notes, stripe_checkout_session_id, stripe_payment_intent_id, paid_at, cancelled_at, created_at, updated_at FROM bookings
WHERE stripe_checkout_session_id = $1
`

func (q *Queries) GetBookingByCheckoutID(ctx context.Context, stripeCheckoutSessionID sql.NullString) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBookingByCheckoutID, stripeCheckoutSessionID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ServiceID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.ServiceName,
		&i.ServicePrice,
		&i.CustomerNotes,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOverlappingBookings = `-- name: GetOverlappingBookings :many
SELECT id, customer_id, service_id, starts_at, ends_at, status, service_name, service_price, customer_notes, stripe_checkout_session_id, stripe_payment_intent_id, paid_at, cancelled_at, created_at, updated_at FROM bookings
WHERE status NOT IN ('cancelled')
  AND starts_at < $1
  AND ends_at > $2
`

type GetOverlappingBookingsParams struct {
	EndsAt   time.Time `json:"ends_at"`
	StartsAt time.Time `json:"starts_at"`
}

func (q *Queries) GetOverlappingBookings(ctx context.Context, arg GetOverlappingBookingsParams) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, getOverlappingBookings, arg.EndsAt, arg.StartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ServiceID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.ServiceName,
			&i.ServicePrice,
			&i.CustomerNotes,
			&i.StripeCheckoutSessionID,
			&i.StripePaymentIntentID,
			&i.PaidAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingToFailed = `-- name: UpdateBookingToFailed :one
UPDATE bookings
SET status = 'payment_failed',
    updated_at = now()
WHERE stripe_payment_intent_id = $1
RETURNING id, customer_id, service_id, starts_at, ends_at, status, service_name, service_price, customer_notes, stripe_checkout_session_id, stripe_payment_intent_id, paid_at, cancelled_at, created_at, updated_at
`

func (q *Queries) UpdateBookingToFailed(ctx context.Context, stripePaymentIntentID sql.NullString) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateBookingToFailed, stripePaymentIntentID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ServiceID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.ServiceName,
		&i.ServicePrice,
		&i.CustomerNotes,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBookingToPaid = `-- name: UpdateBookingToPaid :one
UPDATE bookings
SET status = 'paid',
    stripe_payment_intent_id = $2,
    paid_at = now(),
    updated_at = now()
WHERE stripe_checkout_session_id = $1
RETURNING id, customer_id, service_id, starts_at, ends_at, status, service_name, service_price, customer_notes, stripe_checkout_session_id, stripe_payment_intent_id, paid_at, cancelled_at, created_at, updated_at
`

type UpdateBookingToPaidParams struct {
	StripeCheckoutSessionID sql.NullString `json:"stripe_checkout_session_id"`
	StripePaymentIntentID   sql.NullString `json:"stripe_payment_intent_id"`
}

func (q *Queries) UpdateBookingToPaid(ctx context.Context, arg UpdateBookingToPaidParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateBookingToPaid, arg.StripeCheckoutSessionID, arg.StripePaymentIntentID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ServiceID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.ServiceName,
		&i.ServicePrice,
		&i.CustomerNotes,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
