// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type UserRole string

const (
	UserRoleCustomer UserRole = "customer"
	UserRoleAdmin    UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Booking struct {
	ID                      uuid.UUID      `json:"id"`
	CustomerID              uuid.UUID      `json:"customer_id"`
	ServiceID               uuid.UUID      `json:"service_id"`
	StartsAt                time.Time      `json:"starts_at"`
	EndsAt                  time.Time      `json:"ends_at"`
	Status                  string         `json:"status"`
	ServiceName             string         `json:"service_name"`
	ServicePrice            interface{}    `json:"service_price"`
	CustomerNotes           sql.NullString `json:"customer_notes"`
	StripeCheckoutSessionID sql.NullString `json:"stripe_checkout_session_id"`
	StripePaymentIntentID   sql.NullString `json:"stripe_payment_intent_id"`
	PaidAt                  sql.NullTime   `json:"paid_at"`
	CancelledAt             sql.NullTime   `json:"cancelled_at"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	TokenHash string         `json:"token_hash"`
	ExpiresAt time.Time      `json:"expires_at"`
	CreatedAt time.Time      `json:"created_at"`
	RevokedAt sql.NullTime   `json:"revoked_at"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
}

type Service struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Price          string    `json:"price"`
	Description    string    `json:"description"`
	SessionMinutes int32     `json:"session_minutes"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type ServiceAvailability struct {
	ID        uuid.UUID `json:"id"`
	ServiceID uuid.UUID `json:"service_id"`
	DayOfWeek int16     `json:"day_of_week"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type StripeWebhookEvent struct {
	ID          string    `json:"id"`
	ProcessedAt time.Time `json:"processed_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	Role         UserRole  `json:"role"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
