// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package database

import (
	"context"
)

const createService = `-- name: CreateService :one
INSERT INTO services (name, price, description, session_minutes)
VALUES ($1, $2, $3, $4)
RETURNING id, name, price, description, session_minutes, created_at, updated_at
`

type CreateServiceParams struct {
	Name           string `json:"name"`
	Price          string `json:"price"`
	Description    string `json:"description"`
	SessionMinutes int32  `json:"session_minutes"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, createService,
		arg.Name,
		arg.Price,
		arg.Description,
		arg.SessionMinutes,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Description,
		&i.SessionMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllServices = `-- name: GetAllServices :many
SELECT id, name, price, description, session_minutes, created_at, updated_at FROM services
`

func (q *Queries) GetAllServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, getAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Description,
			&i.SessionMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceByName = `-- name: GetServiceByName :one
SELECT id, name, price, description, session_minutes, created_at, updated_at FROM services
WHERE name = $1
`

func (q *Queries) GetServiceByName(ctx context.Context, name string) (Service, error) {
	row := q.db.QueryRowContext(ctx, getServiceByName, name)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Description,
		&i.SessionMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
