// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stripe.sql

package database

import (
	"context"
)

const createProcessedStripeEvent = `-- name: CreateProcessedStripeEvent :exec
INSERT INTO stripe_webhook_events (id)
VALUES ($1)
`

func (q *Queries) CreateProcessedStripeEvent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, createProcessedStripeEvent, id)
	return err
}

const getStripeEventByID = `-- name: GetStripeEventByID :one
SELECT id, processed_at FROM stripe_webhook_events
WHERE id = $1
`

func (q *Queries) GetStripeEventByID(ctx context.Context, id string) (StripeWebhookEvent, error) {
	row := q.db.QueryRowContext(ctx, getStripeEventByID, id)
	var i StripeWebhookEvent
	err := row.Scan(&i.ID, &i.ProcessedAt)
	return i, err
}
