version: "3"

tasks:
  lint:
    desc: "Run golangci-lint"
    cmds:
      - golangci-lint run

  fmt:
    desc: "Run golangci-lint formatter"
    cmds:
      - golangci-lint fmt

  sqlc:
    desc: "Generate Go code from SQL schema and queries"
    cmds:
      - sqlc generate

  migrate:
    desc: "Run database migrations (up)"
    cmds:
      - goose postgres "postgres://postgres:postgres@localhost:5432/heartcave" up -dir database/migrations

  run:
    desc: "Run the HTTP server"
    cmds:
      - go run ./cmd/http/
