// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_schedule.sql

package db

import (
	"context"
)

const createScheduleEntry = `-- name: CreateScheduleEntry :one
INSERT INTO admin_schedule (day_of_week, start_time, end_time, slot_minutes)
VALUES (?, ?, ?, ?)
RETURNING id, day_of_week, start_time, end_time, slot_minutes, created_at
`

type CreateScheduleEntryParams struct {
	DayOfWeek   int64
	StartTime   string
	EndTime     string
	SlotMinutes int64
}

func (q *Queries) CreateScheduleEntry(ctx context.Context, arg CreateScheduleEntryParams) (AdminSchedule, error) {
	row := q.db.QueryRowContext(ctx, createScheduleEntry,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.SlotMinutes,
	)
	var i AdminSchedule
	err := row.Scan(
		&i.ID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.SlotMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteScheduleEntry = `-- name: DeleteScheduleEntry :exec
DELETE FROM admin_schedule WHERE id = ?
`

func (q *Queries) DeleteScheduleEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteScheduleEntry, id)
	return err
}

const getScheduleByDay = `-- name: GetScheduleByDay :many
SELECT id, day_of_week, start_time, end_time, slot_minutes, created_at FROM admin_schedule WHERE day_of_week = ? ORDER BY start_time ASC
`

func (q *Queries) GetScheduleByDay(ctx context.Context, dayOfWeek int64) ([]AdminSchedule, error) {
	rows, err := q.db.QueryContext(ctx, getScheduleByDay, dayOfWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminSchedule
	for rows.Next() {
		var i AdminSchedule
		if err := rows.Scan(
			&i.ID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.SlotMinutes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedule = `-- name: ListSchedule :many
SELECT id, day_of_week, start_time, end_time, slot_minutes, created_at FROM admin_schedule ORDER BY day_of_week ASC, start_time ASC
`

func (q *Queries) ListSchedule(ctx context.Context) ([]AdminSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedule)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminSchedule
	for rows.Next() {
		var i AdminSchedule
		if err := rows.Scan(
			&i.ID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.SlotMinutes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduleEntry = `-- name: UpdateScheduleEntry :one
UPDATE admin_schedule
SET day_of_week = ?, start_time = ?, end_time = ?, slot_minutes = ?
WHERE id = ?
RETURNING id, day_of_week, start_time, end_time, slot_minutes, created_at
`

type UpdateScheduleEntryParams struct {
	DayOfWeek   int64
	StartTime   string
	EndTime     string
	SlotMinutes int64
	ID          int64
}

func (q *Queries) UpdateScheduleEntry(ctx context.Context, arg UpdateScheduleEntryParams) (AdminSchedule, error) {
	row := q.db.QueryRowContext(ctx, updateScheduleEntry,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.SlotMinutes,
		arg.ID,
	)
	var i AdminSchedule
	err := row.Scan(
		&i.ID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.SlotMinutes,
		&i.CreatedAt,
	)
	return i, err
}
