// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookings.sql

package db

import (
	"context"
	"database/sql"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (customer_id, service_id, date, intentions, status)
VALUES (?, ?, ?, ?, ?)
RETURNING id, customer_id, service_id, date, intentions, status, created_at, updated_at
`

type CreateBookingParams struct {
	CustomerID int64
	ServiceID  int64
	Date       string
	Intentions string
	Status     string
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.CustomerID,
		arg.ServiceID,
		arg.Date,
		arg.Intentions,
		arg.Status,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ServiceID,
		&i.Date,
		&i.Intentions,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :exec
DELETE FROM bookings WHERE id = ?
`

func (q *Queries) DeleteBooking(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBooking, id)
	return err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT
    b.id, b.customer_id, b.service_id, b.date, b.intentions, b.status, b.created_at, b.updated_at,
    c.name AS customer_name,
    c.email AS customer_email,
    c.phone AS customer_phone,
    s.name AS service_name,
    s.description AS service_description,
    s.price AS service_price,
    s.minutes AS service_minutes
FROM bookings b
JOIN customers c ON c.id = b.customer_id
JOIN services s ON s.id = b.service_id
WHERE b.id = ?
LIMIT 1
`

type GetBookingByIDRow struct {
	ID                 int64
	CustomerID         int64
	ServiceID          int64
	Date               string
	Intentions         string
	Status             string
	CreatedAt          string
	UpdatedAt          string
	CustomerName       string
	CustomerEmail      string
	CustomerPhone      string
	ServiceName        string
	ServiceDescription sql.NullString
	ServicePrice       int64
	ServiceMinutes     int64
}

func (q *Queries) GetBookingByID(ctx context.Context, id int64) (GetBookingByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBookingByID, id)
	var i GetBookingByIDRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ServiceID,
		&i.Date,
		&i.Intentions,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.ServiceName,
		&i.ServiceDescription,
		&i.ServicePrice,
		&i.ServiceMinutes,
	)
	return i, err
}

const listBookings = `-- name: ListBookings :many
SELECT
    b.id,
    b.customer_id,
    b.service_id,
    b.date,
    b.intentions,
    b.status,
    b.created_at,
    b.updated_at,
    c.name AS customer_name,
    c.email AS customer_email,
    c.phone AS customer_phone,
    s.name AS service_name,
    s.price AS service_price,
    s.minutes AS service_minutes
FROM bookings b
JOIN customers c ON c.id = b.customer_id
JOIN services s ON s.id = b.service_id
ORDER BY b.date DESC
`

type ListBookingsRow struct {
	ID             int64
	CustomerID     int64
	ServiceID      int64
	Date           string
	Intentions     string
	Status         string
	CreatedAt      string
	UpdatedAt      string
	CustomerName   string
	CustomerEmail  string
	CustomerPhone  string
	ServiceName    string
	ServicePrice   int64
	ServiceMinutes int64
}

func (q *Queries) ListBookings(ctx context.Context) ([]ListBookingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsRow
	for rows.Next() {
		var i ListBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ServiceID,
			&i.Date,
			&i.Intentions,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.ServiceName,
			&i.ServicePrice,
			&i.ServiceMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByCustomer = `-- name: ListBookingsByCustomer :many
SELECT
    b.id, b.customer_id, b.service_id, b.date, b.intentions, b.status, b.created_at, b.updated_at,
    s.name AS service_name,
    s.price AS service_price
FROM bookings b
JOIN services s ON s.id = b.service_id
WHERE b.customer_id = ?
ORDER BY b.date DESC
`

type ListBookingsByCustomerRow struct {
	ID           int64
	CustomerID   int64
	ServiceID    int64
	Date         string
	Intentions   string
	Status       string
	CreatedAt    string
	UpdatedAt    string
	ServiceName  string
	ServicePrice int64
}

func (q *Queries) ListBookingsByCustomer(ctx context.Context, customerID int64) ([]ListBookingsByCustomerRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsByCustomerRow
	for rows.Next() {
		var i ListBookingsByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ServiceID,
			&i.Date,
			&i.Intentions,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceName,
			&i.ServicePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByDate = `-- name: ListBookingsByDate :many
SELECT id, customer_id, service_id, date, intentions, status, created_at, updated_at FROM bookings WHERE date = ? ORDER BY date ASC
`

func (q *Queries) ListBookingsByDate(ctx context.Context, date string) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ServiceID,
			&i.Date,
			&i.Intentions,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByStatus = `-- name: ListBookingsByStatus :many
SELECT
    b.id,
    b.customer_id,
    b.service_id,
    b.date,
    b.intentions,
    b.status,
    b.created_at,
    c.name AS customer_name,
    c.email AS customer_email,
    s.name AS service_name
FROM bookings b
JOIN customers c ON c.id = b.customer_id
JOIN services s ON s.id = b.service_id
WHERE b.status = ?
ORDER BY b.date DESC
`

type ListBookingsByStatusRow struct {
	ID            int64
	CustomerID    int64
	ServiceID     int64
	Date          string
	Intentions    string
	Status        string
	CreatedAt     string
	CustomerName  string
	CustomerEmail string
	ServiceName   string
}

func (q *Queries) ListBookingsByStatus(ctx context.Context, status string) ([]ListBookingsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsByStatusRow
	for rows.Next() {
		var i ListBookingsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ServiceID,
			&i.Date,
			&i.Intentions,
			&i.Status,
			&i.CreatedAt,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBooking = `-- name: UpdateBooking :one
UPDATE bookings
SET customer_id = ?, service_id = ?, date = ?, intentions = ?, status = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
RETURNING id, customer_id, service_id, date, intentions, status, created_at, updated_at
`

type UpdateBookingParams struct {
	CustomerID int64
	ServiceID  int64
	Date       string
	Intentions string
	Status     string
	ID         int64
}

func (q *Queries) UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateBooking,
		arg.CustomerID,
		arg.ServiceID,
		arg.Date,
		arg.Intentions,
		arg.Status,
		arg.ID,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ServiceID,
		&i.Date,
		&i.Intentions,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBookingStatus = `-- name: UpdateBookingStatus :exec
UPDATE bookings
SET status = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateBookingStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBookingStatus, arg.Status, arg.ID)
	return err
}
