// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AdminSchedule struct {
	ID          int64
	DayOfWeek   int64
	StartTime   string
	EndTime     string
	SlotMinutes int64
	CreatedAt   string
}

type Booking struct {
	ID         int64
	CustomerID int64
	ServiceID  int64
	Date       string
	Intentions string
	Status     string
	CreatedAt  string
	UpdatedAt  string
}

type Customer struct {
	ID           int64
	Name         string
	Email        string
	Phone        string
	PasswordHash string
	CreatedAt    string
	UpdatedAt    string
}

type Post struct {
	ID        int64
	Slug      string
	Title     string
	Body      string
	Published int64
	CreatedAt string
	UpdatedAt string
}

type Service struct {
	ID          int64
	Name        string
	Description sql.NullString
	Price       int64
	Minutes     int64
	CreatedAt   string
	UpdatedAt   string
}
