// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stripe_events.sql

package db

import (
	"context"
)

const deleteStripeEvent = `-- name: DeleteStripeEvent :exec
DELETE FROM stripe_events WHERE id = ?
`

func (q *Queries) DeleteStripeEvent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteStripeEvent, id)
	return err
}

const markStripeEventProcessed = `-- name: MarkStripeEventProcessed :exec
UPDATE stripe_events
SET processed_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

func (q *Queries) MarkStripeEventProcessed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markStripeEventProcessed, id)
	return err
}

const recordStripeEvent = `-- name: RecordStripeEvent :one
INSERT OR IGNORE INTO stripe_events (id, event_type)
VALUES (?, ?)
RETURNING id
`

type RecordStripeEventParams struct {
	ID        string
	EventType string
}

func (q *Queries) RecordStripeEvent(ctx context.Context, arg RecordStripeEventParams) (string, error) {
	row := q.db.QueryRowContext(ctx, recordStripeEvent, arg.ID, arg.EventType)
	var id string
	err := row.Scan(&id)
	return id, err
}
